apiVersion: v1
kind: Service
metadata:
  name: platform-api
  labels:
    app: platform-api

spec:
  type: {{ .Values.api.service.type }}

  selector:
    app: platform-api

  ports:
    - name: http
      port: {{ .Values.api.service.port }}
      targetPort: {{ .Values.api.service.port }}
      protocol: TCP