api:
  replicaCount: 2

  image:
    repository: k8s-production-platform-api
    tag: latest
    pullPolicy: IfNotPresent

  config:
    appName: "K8s Production Platform API"
    appEnv: "development"

  service:
    type: ClusterIP
    port: 8000

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

  probes:
    readiness:
      path: /health/ready
      initialDelaySeconds: 5
      periodSeconds: 5

    liveness:
      path: /health/live
      initialDelaySeconds: 10
      periodSeconds: 10

postgres:
  image:
    repository: postgres
    tag: "17-alpine"
    pullPolicy: IfNotPresent

  service:
    port: 5432

  persistence:
    size: 1Gi

  resources:
    requests:
      cpu: 100m
      memory: 128Mi
    limits:
      cpu: 500m
      memory: 512Mi

redis:
  image:
    repository: redis
    tag: "8-alpine"
    pullPolicy: IfNotPresent

  service:
    port: 6379

  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi

ingress:
  enabled: true
  className: nginx
  host: platform.local
  path: /
  pathType: Prefix